### ISSUE TITLE
adobe fonts provider

### ISSUE THREAD

**Issue by danielroe** [nuxt/fonts#11]

**Comment by qwerzl** [comment]
@danielroe If nobody's working on this, I'd love to work on this provider. 

I'm currently thinking about specifying a kit id in the module config, then in `providers/adobe.ts` get the info of this kit (weights, families) as metadata and add all the fonts provided by the kit's CSS if one of the requested fonts matches because Adobe Fonts doesn't provide an endpoint to get CSS for a single font. 

Also, there is an older Adobe Fonts API on https://fonts.adobe.com/docs/api/kits. The newer one requires an API key to access it. Is it okay to use the older API endpoints?

**Comment by danielroe** [comment]
That would be great! It looks like we can use the older API, they just encourage use of the new one.
