### ISSUE TITLE
`@font-face` not used with `fontshare` provider

### ISSUE THREAD

**Issue by samk-dev** [nuxt/fonts#182]
I am using the module with `fontshare` as a provider. When checking `pageInsights` it shows that `@font-face` is not being used. When adding `fontain` module it resolves the issue.

<img width="741" alt="Screenshot 2024-06-22 at 23 39 50" src="https://github.com/nuxt/fonts/assets/33263129/a91b98cd-7b15-4a13-9588-35bd8c0a0366">

<img width="663" alt="Screenshot 2024-06-22 at 22 38 07" src="https://github.com/nuxt/fonts/assets/33263129/0fe5a298-1dd2-4fb3-b476-520be7d2ac08">

when using `fontain`

<img width="964" alt="Screenshot 2024-06-22 at 22 34 07" src="https://github.com/nuxt/fonts/assets/33263129/dca00dbe-a0bc-4163-a55b-e584f97a2506">

- Operating System: `Darwin`
- Node Version:     `v20.14.0`
- Nuxt Version:     `3.12.2`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.6`
- Package Manager:  `npm@10.7.0`
- Builder:          `-`
- User Config:      `devtools`, `future`, `modules`, `runtimeConfig`, `app`, `routeRules`, `devServer`, `build`, `fonts`, `tailwindcss`
- Runtime Modules:  `@nuxt/eslint@0.3.13`, `@nuxtjs/tailwindcss@6.12.0`, `@nuxt/image@1.7.0`, `@nuxt/fonts@0.7.0`, `@nuxtjs/fontaine@0.4.3`
- Build Modules:    `-`

**Comment by danielroe** [comment]
@samk-dev checking this out, it seems the problem is that you aren't using the font anywhere in your app. So by adding the CSS + specifying it should be preloaded, you're asking the browser to add a preload for a font that isn't needed. Maybe I'm misunderstanding - so please do let me know more details and I'll happily reopen.
